# Generated by Django 4.2 on 2023-05-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comm_id',
            new_name='user',
        ),
    ]
