# Generated by Django 4.2 on 2023-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comm_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='info_comm',
            field=models.TextField(max_length=200, null=True, verbose_name="Comment's info"),
        ),
    ]
