# Generated by Django 4.2 on 2023-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=30, null=True, verbose_name='Nickname'),
        ),
    ]
