# Generated by Django 4.2 on 2023-05-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_alter_comment_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="Post's Description"),
        ),
    ]
