# Generated by Django 4.2 on 2023-04-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category Title')),
                ('slug', models.SlugField(max_length=20, verbose_name="Short Category's Name")),
                ('description', models.CharField(max_length=140, verbose_name="Category's Description")),
                ('is_active', models.BooleanField(verbose_name='Category is active?')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Game Name')),
                ('pub_date', models.DateField(verbose_name='Add date')),
                ('release_date', models.DateField(verbose_name='Release Time')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('slug', models.SlugField(max_length=20, verbose_name="Short Game's Name")),
                ('description', models.TextField(verbose_name="Game's Description")),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='Game', verbose_name="Game's Image")),
                ('is_active', models.BooleanField(verbose_name='Game is active?')),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store_games.category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
