# Generated by Django 4.2 on 2023-05-01 20:35

from django.db import migrations, models
import django.db.models.deletion
import store_games.models


class Migration(migrations.Migration):

    dependencies = [
        ('store_games', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Short name category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, default=store_games.models.Category.default_category, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store_games.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='Short name category'),
        ),
    ]
