# Generated by Django 4.2 on 2023-05-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_games', '0003_category_game_amount_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
